name: Daily IBM GitHub Stats Collection and Chart Generation

on:
  schedule:
    # Run daily at 6:00 AM UTC (adjust as needed)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-stats-and-generate-charts:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Collect GitHub stats
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python create_csv.py
        
    - name: Generate charts and index
      run: |
        python generate_charts.py
        
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        
    - name: Commit and push changes
      run: |
        git add ibm_stats.csv charts/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily stats update: $(date '+%Y-%m-%d')"
          git push
        fi
